// <auto-generated />
namespace CurrySupport.DataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class lösung_isnt_required_anymore : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lösung_isnt_required_anymore));
        
        string IMigrationMetadata.Id
        {
            get { return "201606162141531_lösung_isnt_required_anymore"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
