// <auto-generated />
namespace CurrySupport.DataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addseed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addseed));
        
        string IMigrationMetadata.Id
        {
            get { return "201606111044039_add-seed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
